# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import project2.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('user_id', models.IntegerField()),
                ('authenticator', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(default='password', max_length=1000)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', project2.fields.IntegerRangeField()),
                ('comment', models.TextField()),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project2.Custom_User')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DEFAULT_TITLE', max_length=50)),
                ('artists', models.CharField(default='NO_ARTIST', max_length=50)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project2.Custom_User')),
            ],
        ),
        migrations.CreateModel(
            name='Music_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DEFAULT_TITLE', max_length=50)),
                ('artists', models.CharField(default='NO_ARTIST', max_length=50)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project2.Custom_User')),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DEFAULT_TITLE', max_length=50)),
                ('artists', models.CharField(default='NO_ARTIST', max_length=50)),
                ('text', models.TextField(default='text', max_length=1000)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project2.Custom_User')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DEFAULT_TITLE', max_length=50)),
                ('artists', models.CharField(default='NO_ARTIST', max_length=50)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project2.Custom_User')),
            ],
        ),
        migrations.CreateModel(
            name='Spark_Entries',
            fields=[
                ('item_id', models.CharField(default='DEFAULT_ITEM_ID', max_length=50, primary_key=True, serialize=False)),
                ('recommended_items', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DEFAULT_TITLE', max_length=50)),
                ('artists', models.CharField(default='NO_ARTIST', max_length=50)),
                ('text', models.TextField()),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project2.Custom_User')),
            ],
        ),
    ]
