# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-15 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project2.Image'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='music_video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project2.Music_Video'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='poem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project2.Poem'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='song',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project2.Song'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='story',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project2.Story'),
        ),
    ]
