# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-18 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0002_auto_20180215_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='owner',
        ),
        migrations.AlterField(
            model_name='song',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
