# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-19 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0005_song_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='music_video',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='music_video',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='song',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='story',
            name='owner',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='music_video',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
