# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-19 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0006_auto_20180219_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='music_video',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='poem',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='song',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='story',
        ),
    ]
