# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0010_auto_20180219_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
