# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-24 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0011_auto_20180311_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('user_id', models.IntegerField()),
                ('authenticator', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
