# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0012_authenticator'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='password',
            field=models.CharField(default='password', max_length=1000),
        ),
    ]
