# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-18 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0013_custom_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticator',
            name='authenticator',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poem',
            name='text',
            field=models.TextField(default='text', max_length=1000),
        ),
    ]
