# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-06 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0014_auto_20180422_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spark_Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(default='DEFAULT_ITEM_ID', max_length=50)),
                ('recommended_items', django_mysql.models.ListTextField(models.CharField(max_length=20), size=None)),
            ],
        ),
    ]
