# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0015_auto_20180415_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='text',
            field=models.TextField(default='text', max_length=1000),
        ),
    ]
