notifications:
  email: false
language: python
python:
  - 3.5.2
sudo: required

services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  # - create user 'www'@'%' identified by '$3cureUS';
  # - create database cs4501 character set utf8;
  # - grant all on cs4501.* to 'www'@'%';
  # - exit
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker pull mysql:5.7.14

before_script:
  - docker pull mysql:5.7.14

script:
  - cd app
  - pwd
  - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v /home/travis/build/EtonMon/cs4501/app/db:/var/lib/mysql  mysql:5.7.14
  # - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v /home/travis/build/EtonMon/cs4501/app/db:/var/lib/mysql  mysql:5.7.14
  - sudo chmod -R 755 /var/lib/mysql/
  - docker run -it --name mysql-cmdline --link mysql:/home/travis/build/EtonMon/cs4501/app/db mysql:5.7.14 bash -c "mysql -uroot -p"'\$3cureUS'""
  - mysql -uroot -p'\$3cureUS' -h db
  - create user 'www'@'%' identified by '$3cureUS';
  - create database cs4501 character set utf8;
  - grant all on cs4501.* to 'www'@'%';
  - exit
  # - mysql -u USER -pPASSWORD <<EOF
  # - SQL_QUERY 1
  # - SQL_QUERY 2
  # - SQL_QUERY N
  # - EOF
  - docker-compose up <<EOF
  - EOF
