models:
    image: tp33/django
    external_links:
      -  mysql:db
      # -  groupmysql:./db
    volumes:
      - ./test_project/:/app
      # - ~/Documents/uva/isa/cs4501/:/app
    ports:
      - "8001:8000"
#    command: find . -name auto.cnf
#    command: python ./app/test_project/manage.py makemigrations
#    command: python ./app/test_project/manage.py migrate
#    command: python manage.py loaddata db.json
    # command: bash -c "pip install djangorestframework && python ./app/test_project/manage.py makemigrations && python ./app/test_project/manage.py migrate && python ./app/test_project/manage.py loaddata ./app/test_project/db.json && mod_wsgi-express start-server --working-directory /app/app/test_project --reload-on-changes /app/app/test_project/test_project/wsgi.py"
#    command: bash -c "mod_wsgi-express start-server --reload-on-changes --working-directory /app/test_project /app/test_project/test_project/wsgi.py"


    command: bash -c "pip install djangorestframework && python /app/manage.py makemigrations && python /app/manage.py migrate && python /app/manage.py loaddata /app/db.json && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/test_project/wsgi.py"

exp:
    image: tp33/django
    links:
      -  models:models-api

    volumes:
      - ./exp/:/app

    ports:
      - "8002:8000"

    command: bash -c "pip install djangorestframework && python /app/manage.py makemigrations && python /app/manage.py migrate && python /app/manage.py && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/exp/wsgi.py"

web:
    image: tp33/django
    links:
      -  exp:exp-api

    volumes:
      - ./web/:/app

    ports:
      - "8000:8000"

    command: bash -c "pip install djangorestframework && python /app/manage.py makemigrations && python /app/manage.py migrate && python /app/manage.py && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/web/wsgi.py"
