models:
    image: tp33/django
    external_links:
      -  mysql:db
      # -  groupmysql:./db
    volumes:
      - ./test_project/:/app
      # - ~/Documents/uva/isa/cs4501/:/app
    ports:
      - "8001:8000"

    command: bash -c "pip install djangorestframework && python /app/manage.py makemigrations && python /app/manage.py migrate && python /app/manage.py loaddata /app/db.json && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/test_project/wsgi.py"
    # && python /app/manage.py test
exp:
    image: tp33/django
    links:
      -  models:models-api

    volumes:
      - ./exp/:/app

    ports:
      - "8002:8000"

    command: bash -c "pip install djangorestframework && pip install requests && python /app/manage.py makemigrations && python /app/manage.py migrate && python /app/manage.py && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/exp/wsgi.py"
  #pipenv install requests &&

web:
    image: tp33/django
    links:
      -  exp:exp-api

    volumes:
      - ./web/:/app

    ports:
      - "8000:8000"

    command: bash -c "pip install djangorestframework && python /app/manage.py makemigrations && python /app/manage.py migrate && python /app/manage.py && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/web/wsgi.py"
