models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ~/Documents/uva/isa/cs4501:/app
    ports:
      - "8001:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory /app/test_project --reload-on-changes /app/test_project/test_project/wsgi.py"
